fontsize: '28-31'
font_path: 'assets/vnm_fonts'
words: 'assets/corpus/test.txt'
period_prob: 0.15
prob_image: 0.3
prob_table: 0.15
bg_img: 'assets/bg'
img_height: 2000
img_width: 1500

doc_images: 'C:/Users/sonnt72/Downloads/bg_img'
plot_path: 'assets/all_plot'
formula_path: 'assets/formula'
type: 'page'
col_range: '1-3'

col_spacing: '35-50'
spacing: 0.15

tab_at_start: True
blur: True

repeat: 5
print_freq: 10